// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhnkyKaZBuiR6gk5hoSBuPdBARYIZIS4',
    appId: '1:391361093115:web:0d70e7aed32d3f8bffff5e',
    messagingSenderId: '391361093115',
    projectId: 'niet-portal',
    authDomain: 'niet-portal.firebaseapp.com',
    storageBucket: 'niet-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2RgK7XfsfQerAP6gf026g-c_LZDPhKHY',
    appId: '1:391361093115:android:494c0f546fa7e157ffff5e',
    messagingSenderId: '391361093115',
    projectId: 'niet-portal',
    storageBucket: 'niet-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQN1u9rOvhWEKxrqIf3Vq2G4qloEUCzk',
    appId: '1:391361093115:ios:8b833f31bf176a15ffff5e',
    messagingSenderId: '391361093115',
    projectId: 'niet-portal',
    storageBucket: 'niet-portal.firebasestorage.app',
    androidClientId: '391361093115-5n8ecrunog6ecc6qfan9ri47uusl2utv.apps.googleusercontent.com',
    iosClientId: '391361093115-ntkkvfad81ooala2cv2g4ib0v4gpo33q.apps.googleusercontent.com',
    iosBundleId: 'com.example.supabaseImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmQN1u9rOvhWEKxrqIf3Vq2G4qloEUCzk',
    appId: '1:391361093115:ios:8b833f31bf176a15ffff5e',
    messagingSenderId: '391361093115',
    projectId: 'niet-portal',
    storageBucket: 'niet-portal.firebasestorage.app',
    androidClientId: '391361093115-5n8ecrunog6ecc6qfan9ri47uusl2utv.apps.googleusercontent.com',
    iosClientId: '391361093115-ntkkvfad81ooala2cv2g4ib0v4gpo33q.apps.googleusercontent.com',
    iosBundleId: 'com.example.supabaseImage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhnkyKaZBuiR6gk5hoSBuPdBARYIZIS4',
    appId: '1:391361093115:web:b23dd1705af91971ffff5e',
    messagingSenderId: '391361093115',
    projectId: 'niet-portal',
    authDomain: 'niet-portal.firebaseapp.com',
    storageBucket: 'niet-portal.firebasestorage.app',
  );

}